### PR TITLE
Create the Creative Central subprojects

### PR DESCRIPTION
**Pull request by yusshu**
#### Based on feature request #11, solves #11
# Creative Central
A Minecraft server plugin/extension to manage and unify the server's resource-pack

## Progress

- [x] **Event System:** Create the event system and the `ResourcePackGenerateEvent` event
- [x] **Export System:** Create the resource-pack export system *(Could be based on [unemojis' one](https://github.com/unnamed/emojis/tree/main/plugin/src/main/java/team/unnamed/emojis/resourcepack/export))*
- [x] **Configurability:** Create a user-friendly configuration. This includes the `initial-resources` feature specified in #11
- [x] **Actions System:** Add configurable actions that would be executed depending on what happens with the players *(e.g. kick them when they reject the server's resource pack)* 
- [x] **Commands:** Add commands to regenerate the resource-pack and to apply the resource pack *(We could use the @a and @p things)*
- [x] **Documentation:** Documentation for the developer's API and for server administrators *(plugin commands, permissions)*
- [x] Paper Support

### CODE REVIEW

**Comment by yusshu** [comment]
Should we move this to a different repository?

**Comment by dev-hydrogen** [comment]
Should the project have the resource pack hosted on the minecraft server?

**Comment by dev-hydrogen** [comment]
Also would it be possible to implement the resource pack hosting on the proxy, but still allow individual servers to have their own resource packs in case resources need to be changed between servers

**Comment by yusshu** [comment]
> Also would it be possible to implement the resource pack hosting on the proxy, but still allow individual servers to have their own resource packs in case resources need to be changed between servers?

I think it's a good idea and should be implemented

**Comment by yusshu** [comment]
> Should the project have the resource pack hosted on the minecraft server?

I think that it should be an option.
I have already implemented it in the unemojis plugin, see [its configuration](https://github.com/unnamed/emojis/blob/main/plugin/src/main/resources/config.yml#L33)

**Pull request merged**
